import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../../core/shared/widgets/pyago_button.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/app_radius.dart';
import '../../../../core/theme/app_typography.dart';
import '../../../settings/presentation/providers/settings_provider.dart';
import '../providers/auth_provider.dart';

class _OnboardingPage {
  const _OnboardingPage(this.icon, this.title, this.description);
  final IconData icon;
  final String title;
  final String description;
}

const _pages = [
  _OnboardingPage(
    Icons.auto_stories_outlined,
    'Every form of expression',
    'Poetry, journals, voice notes, articles, and photos all live together — no format is a second-class citizen.',
  ),
  _OnboardingPage(
    Icons.tune_rounded,
    'No endless scroll',
    'Pyago surfaces a small, thoughtful set of things worth your attention instead of an infinite feed.',
  ),
  _OnboardingPage(
    Icons.groups_2_outlined,
    'Communities, not followers',
    'Gather around topics and people you care about instead of chasing numbers.',
  ),
  _OnboardingPage(
    Icons.verified_user_outlined,
    'Only Human',
    'Nothing you write here is touched, suggested, or generated by AI. It\'s just you.',
  ),
];

class OnboardingScreen extends ConsumerStatefulWidget {
  const OnboardingScreen({super.key});

  @override
  ConsumerState<OnboardingScreen> createState() => _OnboardingScreenState();
}

class _OnboardingScreenState extends ConsumerState<OnboardingScreen> {
  final _controller = PageController();
  int _index = 0;

  void _finish() {
    ref.read(onboardingCompleteProvider.notifier).state = true;
    context.go('/welcome');
  }

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final isLast = _index == _pages.length - 1;
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final settings = ref.watch(settingsControllerProvider);

    return Scaffold(
      body: Stack(
        fit: StackFit.expand,
        children: [
          // Serene misty background
          Image.asset(
            'assets/images/welcome_bg.png',
            fit: BoxFit.cover,
          ),
          // Gradient scrim
          Container(
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [
                  Colors.black.withOpacity(settings.highContrast ? 0.8 : 0.15),
                  Colors.black.withOpacity(settings.highContrast ? 0.9 : 0.4),
                  Colors.black.withOpacity(settings.highContrast ? 0.95 : 0.75),
                ],
                begin: Alignment.topCenter,
                end: Alignment.bottomCenter,
              ),
            ),
          ),
          SafeArea(
            child: Column(
              children: [
                Align(
                  alignment: Alignment.topRight,
                  child: Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                    child: TextButton(
                      onPressed: _finish,
                      child: Text(
                        'Skip',
                        style: TextStyle(
                          color: Colors.white,
                          fontWeight: FontWeight.bold,
                          fontSize: settings.simpleMode ? 18 : 14,
                        ),
                      ),
                    ),
                  ),
                ),
                Expanded(
                  child: PageView.builder(
                    controller: _controller,
                    itemCount: _pages.length,
                    onPageChanged: (i) => setState(() => _index = i),
                    itemBuilder: (context, i) {
                      final page = _pages[i];
                      return Center(
                        child: Padding(
                          padding: const EdgeInsets.symmetric(horizontal: 24),
                          child: ClipRRect(
                            borderRadius: BorderRadius.circular(AppRadius.lg),
                            child: BackdropFilter(
                              filter: ImageFilter.blur(sigmaX: 16, sigmaY: 16),
                              child: Container(
                                padding: EdgeInsets.symmetric(
                                  horizontal: 24,
                                  vertical: settings.simpleMode ? 28 : 36,
                                ),
                                decoration: BoxDecoration(
                                  color: (isDark ? AppColors.darkSurface : Colors.white)
                                      .withOpacity(isDark ? 0.85 : 0.9),
                                  borderRadius: BorderRadius.circular(AppRadius.lg),
                                  border: Border.all(
                                    color: (isDark ? Colors.white : Colors.black).withOpacity(0.15),
                                    width: settings.highContrast ? 2.5 : 1.0,
                                  ),
                                ),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  children: [
                                    Container(
                                      padding: EdgeInsets.all(settings.simpleMode ? 20 : 16),
                                      decoration: BoxDecoration(
                                        color: scheme.primary.withOpacity(0.12),
                                        shape: BoxShape.circle,
                                      ),
                                      child: Icon(
                                        page.icon,
                                        size: settings.simpleMode ? 64 : 48,
                                        color: scheme.primary,
                                      ),
                                    ),
                                    const SizedBox(height: 24),
                                    Text(
                                      page.title,
                                      textAlign: TextAlign.center,
                                      style: AppTypography.serifDisplay(
                                        color: isDark ? AppColors.darkTextPrimary : AppColors.lightTextPrimary,
                                        fontSize: settings.simpleMode ? 30 : 26,
                                      ),
                                    ),
                                    const SizedBox(height: 14),
                                    Text(
                                      page.description,
                                      textAlign: TextAlign.center,
                                      style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                                            color: isDark ? AppColors.darkTextSecondary : AppColors.lightTextSecondary,
                                            height: 1.5,
                                            fontSize: settings.simpleMode ? 18 : 14,
                                            fontWeight: settings.highContrast ? FontWeight.bold : FontWeight.normal,
                                          ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ),
                        ),
                      );
                    },
                  ),
                ),
                const SizedBox(height: 20),
                // Page indicator dots
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: List.generate(
                    _pages.length,
                    (i) => AnimatedContainer(
                      duration: const Duration(milliseconds: 250),
                      margin: const EdgeInsets.symmetric(horizontal: 5),
                      width: i == _index ? 24 : 8,
                      height: 8,
                      decoration: BoxDecoration(
                        color: i == _index ? Colors.white : Colors.white.withOpacity(0.4),
                        borderRadius: BorderRadius.circular(4),
                      ),
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 32),
                  child: PyagoButton(
                    label: isLast ? 'Get started' : 'Next',
                    variant: PyagoButtonVariant.gradient,
                    size: settings.simpleMode ? PyagoButtonSize.large : PyagoButtonSize.medium,
                    onPressed: () {
                      if (isLast) {
                        _finish();
                      } else {
                        _controller.nextPage(
                          duration: const Duration(milliseconds: 400),
                          curve: Curves.easeOutCubic,
                        );
                      }
                    },
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
